### ISSUE TITLE
The spyglasss button is confusing

### ISSUE THREAD

**Issue by da2x** [rafaelmardojai/share-preview#29]
“Hm. There’s a search field at the bottom of the dialog. I wonder what it does. Oh, it shows more details and not search.”

Please consider picking a different icon (the [circled i](https://www.fileformat.info/info/unicode/char/1F6C8/index.htm) for information, perhaps) or just spell out “Details” or “&lt;meta>” instead?

Version 0.2.0 via Flathub.

**Comment by rafaelmardojai** [comment]
The icon was trying to represent "inspecting", since the dialog shows a bit more than metadata (and I plan to add more things later). 

Maybe adding a label next to the icon could help?

**Comment by da2x** [comment]
> The icon was trying to represent "inspecting", since the dialog shows a bit more than metadata (and I plan to add more things later).

The spyglass is universally recognized to represent search. The box kind of looks like one of those text fields that expands when you click on it, reinforcing the effect.

Apple uses the circle information-i symbol for Inspect, but I’m not aware of any other software using it, though.

> Maybe adding a label next to the icon could help?

I’d go for `<meta>`, `Metadata`, or `Details`. In context, I’d say that the first variant is probably the best one, even though it’s a terrible button label.

**Comment by nekohayo** [comment]
...or you could just use a labelled button instead of relying on abstract icon metaphors that the user must guess. There's plenty of available horizontal space for a one-word label, currently the icon-based button doesn't even use ⅕ of the window's available width. I don't think an icon is necessary at all if you have the label there.
