### ISSUE TITLE
og:image previews fail for WebP images

### ISSUE THREAD

**Issue by da2x** [rafaelmardojai/share-preview#33]
Facebook, Reddit (#12), and Twitter supports WebP images in og:image (and twitter:image), but the app shows an o-slash icon instead.

It’s probably correct to show the o-slash and a warning for Mastadon as support varies depending on the ImageMagic version installed on each server instance (upstream issue #14983).

**Comment by rafaelmardojai** [comment]
The fact of checking if the image format is supported by the service sounds like something we should do.

But I think this concrete issue is because the toolkit texture loader doesn't support WebP. I will see what can I do.

**Comment by pauloxnet** [comment]
I know this issue is closed but I have the same error for unsupported WebP images and I don't think it's correct to open a new one.

**Comment by rafaelmardojai** [comment]
> I know this issue is closed but I have the same error for unsupported WebP images and I don't think it's correct to open a new one.

The issue is open. I have fixed it locally but haven't had time to push the fixes yet.

**Comment by pauloxnet** [comment]
> > I know this issue is closed but I have the same error for unsupported WebP images and I don't think it's correct to open a new one.
> 
> The issue is open. I have fixed it locally but haven't had time to push the fixes yet.

Thanks. If you need someone to help reviewing the PRs I'll be glad to do that. I'm a Python developer but I'm learning Rust since few weeks.

**Comment by rafaelmardojai** [comment]
The app now should try to convert any WebP to PNG before passing it to GTK.
