### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/share-preview#4]
We need a proper icon to release a first version.

**Comment by rafaelmardojai** [comment]
@bertob pinning you in case you can help :P 

Also in other topic, do you have some ideas for the app summary?

**Comment by bertob** [comment]
Here's a first attempt:

![image](https://user-images.githubusercontent.com/1908896/118562442-fafa7100-b76c-11eb-883c-23f1046248a4.png)

As for the summary, maybe something like "Test social media cards locally"?

**Comment by rafaelmardojai** [comment]
> Here's a first attempt:

I definitely like it! If you think it's good enough go for it :P 

 > As for the summary, maybe something like "Test social media cards locally"?

Sounds good to me, I will go with it.
