### ISSUE TITLE
Low contrast with metadata icon

### ISSUE THREAD

**Issue by TheEvilSkeleton** [rafaelmardojai/share-preview#40]
There is low contrast with the metadata icon when using dark style:

![image](https://user-images.githubusercontent.com/50847364/184558645-502e0a28-b6db-4d26-8c98-ad2fdefa1032.png)

![image](https://user-images.githubusercontent.com/50847364/184558652-faea5653-d46b-410c-8078-69b3a71566a2.png)

**Comment by rafaelmardojai** [comment]
Yup, this is fixed in `master` since may, just haven't had the time to do a release 😅.

**Comment by TheEvilSkeleton** [comment]
You're right. I didn't bother looking at the closed issues so my apologies on that. I'll just say it's a duplicate of https://github.com/rafaelmardojai/share-preview/issues/34 and close the issue. Thanks!
