### ISSUE TITLE
Discourse forums preview

### ISSUE THREAD

**Issue by nekohayo** [rafaelmardojai/share-preview#43]
I don't know if there's a way to simulate this too, but it would be pretty nice to be able to preview what a link may look like when shared on a [Discourse](https://discourse.org) forum, because the way it previews tends to be very different from the rest of social media, and it has progressively become the most popular modern open source forum software (and that's [what GNOME uses for its forums](https://discourse.gnome.org), like many other communities use nowadays).

**Comment by rafaelmardojai** [comment]
Initial support landed on master.
