### ISSUE TITLE
Feature Request: Mastodon support

### ISSUE THREAD

**Issue by TheOPtimal** [rafaelmardojai/share-preview#50]
Any chance for Mastodon support in this?

**Comment by rafaelmardojai** [comment]
It does support Mastodon.

**Comment by TheOPtimal** [comment]
oh, sorry.

**Comment by TheOPtimal** [comment]
sorry, i meant Misskey

**Comment by rafaelmardojai** [comment]
> sorry, i meant Misskey

You know if it is very different to Mastodon? I don't want to add more platforms if they just look the same.
