### ISSUE TITLE
Discord event banners

### ISSUE THREAD

**Issue by GeorgesStavracas** [rafaelmardojai/share-preview#54]
The Discord chatting app supports scheduling events with fancy banners, have a look:

![obfuscated banner 1](https://user-images.githubusercontent.com/3518204/225148420-7745ac2d-9518-405c-93b7-6dfa51cefded.png)

![obfuscated banner 2](https://user-images.githubusercontent.com/3518204/225148408-092c8b42-2b31-4587-b303-f8179522922f.png)

Is this a good fit for Share Preview?

**Comment by rafaelmardojai** [comment]
Hmm, this app is more about previewing links, and inspecting their HTML metadata.

Your talking about previewing a static banner by setting image, name, etc. right?

**Comment by GeorgesStavracas** [comment]
People can share Discord events as links - the share button just puts a link in the clipboard - and these events are displayed like the second image when you paste the link in the chat view.

**Comment by rafaelmardojai** [comment]
> People can share Discord events as links - the share button just puts a link in the clipboard - and these events are displayed like the second image when you paste the link in the chat view.

Have you checked how these links look when shared on other platforms? I mean, presumably the data is retrieved internally by Discord. I guess I will need one of those links and try to inspect it.

**Comment by GeorgesStavracas** [comment]
I'm afraid I have no further information on how these links work, or if the event data is private to Discord or not, sorry

**Comment by rafaelmardojai** [comment]
> I'm afraid I have no further information on how these links work, or if the event data is private to Discord or not, sorry

No prob. There is another request to add support for discord chat links preview. I guess if I get to work on that I could special case these links if the data is public.

**Comment by rafaelmardojai** [comment]
Yeah, the events links doesn't provide any metadata, they have normal metadata as an invite link.

Maybe I could to extract the event ID from the url to use some Discord API to get the events details, but that's definitely out of scope.
