### ISSUE TITLE
Can't add new language on Weblate

### ISSUE THREAD

**Issue by bragefuglseth** [rafaelmardojai/share-preview#70]
Hi! I'd like to contribute Norwegian translations to the app, but I can't add Norwegian as a language on Weblate. Could you loosen the restrictions on the Weblate page or add Norwegian manually? :smiley:

**Comment by rafaelmardojai** [comment]
Sure I can add it manually, but the restriction seems strange. You sure by going to Components -> Share Preview you don't have the plus (+) icon to add a new language?

**Comment by bragefuglseth** [comment]
No, not even when logged in:

![Skjermbilde fra 2024-03-07 08-01-41](https://github.com/rafaelmardojai/share-preview/assets/91388039/537aece3-8b9a-4336-8870-8b6fa9a4a01c)

**Comment by rafaelmardojai** [comment]
> No, not even when logged in:

There's no add button when you're directly in languages, you need to go to `Components` -> `Share Preview `.

**Comment by bragefuglseth** [comment]
It works now, thanks!
