### ISSUE TITLE
Crashes when trying to preview https://cockpit-project.org/

### ISSUE THREAD

**Issue by garrett** [rafaelmardojai/share-preview#8]
I get a crash every time when I try to preview https://cockpit-project.org/ or one of its blog posts, such as https://cockpit-project.org/blog/cockpit-244.html

I'm not sure if something is just wildly wrong with what I'm doing on website or if I just happen to triggering an issue in Share Preview. (Either way, Share Preview shouldn't crash.)

And also: thanks for this app! It looks very useful. I'm looking forward to finally fixing https://github.com/cockpit-project/cockpit-project.github.io/issues/224 (it's been on my TODO backburner for quite some time), thanks to Share Preview.

**Comment by rafaelmardojai** [comment]
Thanks for the report! I'm going to check what's causing the issue.

**Comment by rafaelmardojai** [comment]
Ok, the issue is caused because Share Preview is always expecting a valid URL on the `og:image` meta tag.

Fix coming soon.

**Comment by rafaelmardojai** [comment]
Fixed. I'm doing a fix bug release later today.

![Captura de pantalla de 2021-05-25 08-48-32](https://user-images.githubusercontent.com/6210397/119509198-0b46b900-bd36-11eb-8846-01dbeff1ba53.png)

**Comment by garrett** [comment]
Thank you! I'm looking forward to it.
